

#' Fit split model
#'
#' @param simdata List generated by \code{\link{simul_data}}.
#'
#' @return A data frame with 4 columns (intercept estimate and standard error, and slope estimate and standard error), and as many rows as taxa.
#' @export
#' @import dplyr

fit_split <- function(simdata) {

  df <- simdata$data2model

  split.model <- df %>%
    group_by(taxon) %>%
    do(split.m = glm(presabs ~ env, data = ., family = binomial)) %>%
    summarise(interc.split = coef(split.m)[1],
              interc.split.se = se.coef(split.m)[1],
              slope.split = coef(split.m)[2],
              slope.split.se = se.coef(split.m)[2])

}


#' Fit lump model
#'
#' @param simdata List generated by \code{\link{simul_data}}.
#'
#' @return A data frame with 4 columns (intercept estimate and standard error, and slope estimate and standard error), and as many rows as taxa.
#' @export
#' @import dplyr

fit_lump <- function(simdata) {

  df <- simdata$data2model

  lump.model <- df %>%
    group_by(nspp) %>%
    do(lump.m = glm(presabs ~ env, data = ., family = binomial)) %>%
    summarise(interc.lump = coef(lump.m)[1],
              interc.lump.se = se.coef(lump.m)[1],
              slope.lump = coef(lump.m)[2],
              slope.lump.se = se.coef(lump.m)[2])


  lump.df <- lump.model
  for (i in 2:unique(simdata$simdf$nspp)) {
    lump.df <- bind_rows(lump.df, lump.model)
  }

}



#' Fit mixed model (lme4)
#'
#' @param simdata List generated by \code{\link{simul_data}}.
#'
#' @return A data frame with 4 columns (intercept estimate and standard error, and slope estimate and standard error), and as many rows as taxa.
#' @export
#' @import dplyr

fit_mixed <- function(simdata) {

  df <- simdata$data2model

  mixed.model <- lme4::glmer(presabs ~ env + (1 + env | taxon), data = df, family = binomial)
  mixed.params <- broom::tidy(mixed.model, effects = "ran_modes")
  intercs <- mixed.params[mixed.params$term == "(Intercept)", 4:5]
  slopes <- mixed.params[mixed.params$term == "env", 4:5]
  mixed.pars <- data.frame(intercs, slopes)
  names(mixed.pars) <- c("interc.mixed", "interc.mixed.se", "slope.mixed", "slope.mixed.se")
  mixed.pars

}



#' Fit Bayesian phylogenetic mixed model (brms)
#'
#' @param simdata List generated by \code{\link{simul_data}}.
#'
#' @return A data frame with 4 columns (intercept estimate and standard error, and slope estimate and standard error), and as many rows as taxa.
#' @export
#' @import brms

fit_pglmm <- function(simdata, delta = 0.96) {

  phy <- simdata$phylog
  inv.phylo <- MCMCglmm::inverseA(phy, nodes = "TIPS", scale = TRUE)
  A <- solve(inv.phylo$Ainv)
  rownames(A) <- rownames(inv.phylo$Ainv)

  df <- simdata$data2model

  pglmm <- brms::brm(
    presabs ~ env + (1 + env | taxon),
    data = df,
    family = bernoulli(),
    cov_ranef = list(taxa = A),
    prior = c(
      prior(normal(0, 3), "b"),
      prior(normal(0, 3), "Intercept"),
      prior(student_t(3, 0, 3), "sd")),  # sd of group random effect
    chains = 3, cores = 3, iter = 4000,
    control = list(adapt_delta = delta)
  )

  pglmm.params <- data.frame(coef(pglmm)$taxon[, , "Intercept"][, 1:2],
                             coef(pglmm)$taxon[, , "env"][, 1:2])
  names(pglmm.params) <- c("interc.pglmm", "interc.pglmm.se", "slope.pglmm", "slope.pglmm.se")

  pglmm.params

}
